#!/bin/bash

function fzf-kill-processes() {
  local pid
  pid=$(ps -ef | sed 1d | fzf -m | awk '{print $2}')

  if [ "x$pid" != "x" ]
  then
    echo $pid | xargs kill -${1:-9}
  fi
}

function fzf-find-files(){
  local file=$(find . | fzf --multi --reverse)
  if [[ $file ]]; then
    for prog in $(echo $file);
    do; $EDITOR $prog; done;
  else
    echo "cancelled fzf"
  fi
}
