#!/bin/sh

export XDG_CONFIG_HOME=$HOME/.config
export XDG_DATA_HOME=$HOME/.local/share
export XDG_CACHE_HOME=$HOME/.cache

# == Programs ==

export EDITOR="nvim"

# ==============

# == Paths ==

export PATH="$PATH:$(find ~/.local/bin -type d | paste -sd ':' -)"
export GOPATH="$HOME/.local/go"
export RUSTUP_HOME="$XDG_DATA_HOME/rustup"
export GOBIN="$HOME/.local/bin"
export CARGO_HOME="$XDG_DATA_HOME/cargo"
export POETRY_HOME="~/.local/poetry"
export ANSIBLE_HOME="${XDG_CONFIG_HOME}/ansible"

# ===========

# == ZSH Shell ==

export ZDOTDIR="$XDG_CONFIG_HOME/zsh"

# == Program-specific tweaks ==

export BAT_THEME="Catppuccin Mocha"
export FZF_DEFAULT_COMMAND='rg --files'
export FZF_DEFAULT_OPTS="
--color=bg+:#313244,bg:#181825,spinner:#f5e0dc,hl:#f38ba8 \
--color=fg:#cdd6f4,header:#f38ba8,info:#cba6f7,pointer:#f5e0dc \
--color=marker:#b4befe,fg+:#cdd6f4,prompt:#cba6f7,hl+:#f38ba8 \
--multi \
--preview='batcat --style=numbers --color=always --line-range :500 {}' --preview-window right:noborder"

# =============================

# == Clean up ==

export NOTMUCH_CONFIG="$XDG_CONFIG_HOME/notmuch-config"
export ANSIBLE_CONFIG="${XDG_CONFIG_HOME}/ansible.cfg"
export ANSIBLE_GALAXY_CACHE_DIR="${XDG_CACHE_HOME}/ansible/galaxy_cache"
export XAUTHORITY="/tmp/.Xauthority"
export WEGORC="$XDG_CONFIG_HOME/wego/.wegorc"
export DOCKER_CONFIG="$XDG_CONFIG_HOME/docker"
export PYTHON_EGG_CACHE="$XDG_CACHE_HOME/python-eggs"
export IPYTHONDIR="$XDG_CONFIG_HOME/jupyter"
export WGETRC="$XDG_CONFIG_HOME/wget/wgetrc"
export NODE_REPL_HISTORY="$XDG_DATA_HOME/node_repl_history"
export NPM_CONFIG_USERCONFIG="$XDG_CONFIG_HOME/npm/npmrc"
export PSQLRC="$XDG_CONFIG_HOME/pg/psqlrc"
export PSQL_HISTORY="$XDG_CACHE_HOME/pg/psql_history"
export PGPASSFILE="$XDG_CONFIG_HOME/pg/pgpass"
export PGSERVICEFILE="$XDG_CONFIG_HOME/pg/pg_service.conf"
export NPM_CONFIG_USERCONFIG="$XDG_CONFIG_HOME/npm/npmrc"
export JUPYTER_CONFIG_DIR="$XDG_CONFIG_HOME/jupyter"
export NVM_DIR="$XDG_DATA_HOME/nvm"

# ==============

