#!/bin/sh

alias config='/usr/bin/git --git-dir=$HOME/.manager/ --work-tree=$HOME'

alias cp="cp -iv"
alias mv="mv -iv"
alias rm="rm -vI"
alias ls="exa -la"
alias cat="$(command -v bat >/dev/null 2>&1 && echo 'bat' || echo 'batcat')"

